### ISSUE TITLE
Feature: Log application server IP

### ISSUE THREAD

**Issue by comes** [bilfeldt/laravel-request-logger#25]
Feature Request:

Please log the IP of the server who's handling the request.

Especially if you have an architecture with multiple app servers and a load balancer in front, it's nearly impossible to figure out which app server was responsible for this request.

**Comment by bilfeldt** [comment]
@comes Do you have any suggestions to how to do this?

**Comment by bilfeldt** [comment]
Would the easiest not be to add this info to the request header using a middleware, which would automatically log it already?

Relevant info could be:

```php
phpversion(); 
gethostname();
request()->server('SERVER_ADDR');
```

**Comment by comes** [comment]
I would not add it to the request header, because it suggests that it is already part of the header.

as you already have a duration and memory column, I suggest adding a `server_ip` column. hostname or phpversion is out of interest IMO, because the project, which has this package installed, is always on the same PHP version.

**Comment by bilfeldt** [comment]
Currently this can be done by overriding the RequestLog model (which can extend the one provided by the package) and new fields can be added. Alternatively one can also
implement a complete new Logger.

I do think the next major version will implement a more simple way of adding more context to the log, perhaps using a json field, but this is not currently being developed.
