### ISSUE TITLE
PHP 8.3 Support needed

### ISSUE THREAD

**Issue by prof-usman** [bilfeldt/laravel-request-logger#27]
### PHP8.3 Support

When on PHP 8.3, it gives error

### Your environment

Ubuntu 23, PHP 8.3

Problem 1
    - Root composer.json requires bilfeldt/laravel-request-logger * -> satisfiable by bilfeldt/laravel-request-logger[v0.1.0, v0.2.0, v0.3.0, v1.0.0, v1.0.1, v1.0.2, v1.1.0, v2.0.0, v2.1.0, v2.2.0, v3.0.0].
    - bilfeldt/laravel-request-logger v3.0.0 requires php ~8.1.0 || ~8.2.0 -> your php version (8.3.1; overridden via config.platform, same as actual) does not satisfy that requirement.
  Problem 2
    - bilfeldt/laravel-route-statistics is locked to version v3.0.0 and an update of this package was not requested.
    - bilfeldt/laravel-route-statistics v3.0.0 requires php ~8.1.0 || ~8.2.0 -> your php version (8.3.1; overridden via config.platform, same as actual) does not satisfy that requirement

**Comment by bilfeldt** [comment]
Added in [v3.1.0](https://github.com/bilfeldt/laravel-request-logger/releases/tag/v3.1.0)
