### ISSUE TITLE
ignoredPaths still get logged

### ISSUE THREAD

**Issue by eelco2k** [bilfeldt/laravel-request-logger#29]
The ignored paths still get logged in db. For example /filament/update and /_debugbar/open.

this is my config array for ignored_paths: 

```
'ignore_paths' => [
        '_debugbar*',
        'debugbar*',
        'telescope',
        'telescope-api*',
        'horizon*',
        'nova-api*',
        'livewire*',
    ],
```

I'm having multiple log drivers so maybe that makes it still log to db.... 

I used the Middleware method and added it to Kernel.php.

in the Listeners/LogRequest.php there is a if check but the logging is done after the if.

```
if ($this->shouldLog($event->request, $event->response)) {
            $event->request->enableLog();
}

foreach (array_unique($event->request->attributes->get('log', [])) as $driver) {
                RequestLoggerFacade::driver($driver)->log(
                    $event->request,
                    $event->response,
                    $duration,
                    $memory
                );
            }
```

when i move the foreach within the if statement no more logs for ignored items.

like so:

```
if ($this->shouldLog($event->request, $event->response)) {
            $event->request->enableLog();
            
            foreach (array_unique($event->request->attributes->get('log', [])) as $driver) {
                RequestLoggerFacade::driver($driver)->log(
                    $event->request,
                    $event->response,
                    $duration,
                    $memory
                );
            }
}

```

**Comment by bilfeldt** [comment]
> I see that when using the Middleware it executes the Request Macro 'enableLog', so via that way enableLog is already enabled.  so it doesn't matter  if ($this->shouldLog($event->request, $event->response) == true / false), it will always be enabled an therefor also log all events in the foreach

Correct. This is expected behaviour.

**Comment by eelco2k** [comment]
So when enabled via middleware all configs will be ignored… not only ignored paths but also allowed methods etc…

**Comment by bilfeldt** [comment]
> So when enabled via middleware all configs will be ignored… not only ignored paths but also allowed methods etc… 

Correct. Use **either** middleware or config approach.
