### ISSUE TITLE
Laravel 11 Support Needed

### ISSUE THREAD

**Issue by prof-usman** [bilfeldt/laravel-request-logger#34]
### Laravel 11 Support Needed

Root composer.json requires bilfeldt/laravel-route-statistics ^3.1 -> satisfiable by bilfeldt/laravel-route-statistics[v3.1.0, v3.2.0].

**Comment by bilfeldt** [comment]
@prof-usman upgrade to version [3.2.0](https://github.com/bilfeldt/laravel-request-logger/releases/tag/v3.2.0)
