### ISSUE TITLE
Custom Redis/file driver

### ISSUE THREAD

**Issue by abdokouta** [bilfeldt/laravel-request-logger#35]
how to create custom Redis or File driver?

**Comment by bilfeldt** [comment]
You can use a custom driver like explained here: https://github.com/bilfeldt/laravel-request-logger?tab=readme-ov-file#extending-with-custom-drivers

The custom driver must implement the `Bilfeldt\RequestLogger\Contracts\RequestLoggerInterface` and be registered on the `Bilfeldt\RequestLogger\RequestLogger` class which extends the `Illuminate\Support\Manager`.

You can read more details on Laravels Manager pattern [here](https://ahmedash.dev/blog/laravel-core-patterns/manager-pattern/).
